name: Scorecard supply-chain security
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
     contents: read
     security-events: write
     actions: read
     
    steps:
      - name: Run Scorecard
        uses: ossf/scorecard-action@v2
