name: Scorecard supply-chain security
on:
  push:
    branches: [ "main" ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    
    permissions:
     contents: read
     security-events: write
     
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Scorecard
        uses: ossf/scorecard-action@v2
        with:
         results_file: results.sarif
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        
